### ISSUE TITLE
MVX payment cron not there

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#108]
https://watch.screencastify.com/v/VNK4ZpljFPgmQwaoSYvD

**Comment by cool-raju** [comment]
fixed

**Comment by moumitahalder** [comment]
Still Missing : https://drive.google.com/file/d/1jPjTnFvqBHaYvutb61NVVmLiv2rtIZox/view

**Comment by cool-raju** [comment]
please run setup widget and try again. from status and tools

**Comment by cool-raju** [comment]
fixed
